name: ahmet_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.5.3
  readmore: ^2.2.0
  intl: ^0.18.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  email_validator: ^2.1.17
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.14.0
  logger: ^2.0.2+1
  permission_handler: ^11.3.0
  health: ^9.0.1
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.6.0
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.1
  flutter_datetime_picker: ^1.5.1
  hexcolor: ^3.0.1
  geolocator: ^11.0.0
  firebase_messaging: ^14.7.10
  pedometer: ^4.0.1
  flutter_highlighter: ^0.1.1
  flutter_spinkit: ^5.2.0
dev_dependencies:
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/logi.png
    - assets/images/AnagirisLogo.png

    - assets/images/zyro-image.png
  fonts:
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
